services:

  php-fpm:
    build: .
    container_name: nws-endpoints
    restart: unless-stopped
    volumes:
      - ./watchfolder:/app/data/watchfolder
      - ./db:/app/data/db
    #networks:
    #  - web

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlite_browser
    restart: unless-stopped
    ports:
      - 8888:3000
    volumes:
      - ./db:/config
    networks:
      - web 

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    profiles:
      - test
    command:
      - serve
    volumes:
      - ntfy/cache/ntfy:/var/cache/ntfy
      - ntfy/:/etc/ntfy
    environment:
      - TZ=America/Indiana/Indianapolis
    networks:
      - web

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test:
        - CMD
        - /dozzle
        - healthcheck
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - web

networks:
  web:
    name: web